### PR TITLE
Fix spelling mistakes

### PR DESCRIPTION
**Pull request by shanetj**
Fix spelling  from Retreiving to Retrieving in 7 files

(My first time doing pull request, sorry if i messed anything up)

### CODE REVIEW

**Comment by nmelhado** [comment]
31 years on this Earth, and I still somehow managed to mess this up! If you fix the conflict (News instead of Rosters) in `src/routes/resources/index.svelte` I'll merge this in. Thanks for the help!

**Comment by nmelhado** [comment]
> Fix spelling from Retreiving to Retrieving in 7 files
> 
> (My first time doing pull request, sorry if i messed anything up)

You did it perfectly! I just happened to also change `src/routes/resources/index.svelte` to change 'roster data' to 'fantasy news' which caused a conflict

**Review by shanetj — COMMENTED** [review]
i think this is what is needed, right?

**Comment by nmelhado** [comment]
Merged. Thank you!

**Pull request merged**
